<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <ContainerPort>8080</ContainerPort>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
